### PR TITLE
Few Optimizations

### PR DESCRIPTION
**Pull request by vivekkiran**
Changed  gradleVersion to  '2.4'
Changed ActionBarActivity to AppCompatActivity
https://plus.google.com/+AndroidDevelopers/posts/LNyDnnBYJ8r
http://stackoverflow.com/questions/30083892/diffrence-between-appcompact-activity-and-actionbar-activity
Upgraded Version of AppCompat Library in samples to the latest version.
https://chris.banes.me/2015/04/22/support-libraries-v22-1-0/

### CODE REVIEW

**Comment by vivekkiran** [comment]
https://travis-ci.org/twitter/digits-android/builds/68604474#L918

**Comment by rallat** [comment]
Thanks for your contribution!
We'll review the PR shortly.

**Comment by efrohnhoefer** [comment]
Hi @vivekkiran, Again thank you for you contribution. We are unable to merge the PR due to a theming bug in the most recent version of the appcompat library. If we were to upgrade we would force all our user to move to the latest version. 

See: [Issue 8](https://github.com/twitter/digits-android/issues/8)

**Comment by efrohnhoefer** [comment]
If you wouldn't mind splitting your Gradle changes from the appcompat library changes we would gladly accept the PR. Once the issues with the appcompat library is resolved we could accept appcompat version bump.

**Pull request closed without merging**
